# Generated by Django 2.0.2 on 2018-05-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefones',
            name='pessoa',
            field=models.CharField(default='', max_length=30, verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='telefones',
            name='num',
            field=models.CharField(default='', max_length=15, unique=True, verbose_name='Número'),
        ),
    ]
