# Generated by Django 2.0.2 on 2019-03-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscal',
            name='planilha',
            field=models.FileField(max_length=200, upload_to='uploads/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='cfop',
            field=models.CharField(max_length=4, verbose_name='CFOP'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='codigo_Produto',
            field=models.CharField(max_length=20, verbose_name='Cod. Produto'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='cst',
            field=models.CharField(max_length=3, verbose_name='CST'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='desd',
            field=models.CharField(max_length=1, verbose_name='desd.'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='especie',
            field=models.CharField(max_length=5, verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='ncm',
            field=models.CharField(max_length=8, verbose_name='NCM'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='numero_Item',
            field=models.CharField(max_length=3, verbose_name='Num. Item'),
        ),
    ]
