# Generated by Django 2.0.2 on 2018-05-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificados',
            name='password',
            field=models.CharField(default='', max_length=30, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='validade',
            field=models.DateField(verbose_name='Validade'),
        ),
    ]
