# Generated by Django 2.0.2 on 2018-05-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0002_auto_20180504_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificados',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email da Compra'),
        ),
    ]
