# Generated by Django 2.0.2 on 2019-03-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0003_auto_20180507_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificados',
            name='name',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Nome'),
        ),
    ]
