# Generated by Django 2.0.2 on 2018-05-04 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=30, verbose_name='Usuário')),
                ('password', models.CharField(default='', max_length=30, verbose_name='Senha')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Empresa')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Tipo_usuario')),
            ],
        ),
    ]
