# Generated by Django 2.0.2 on 2018-05-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='cod_acesso',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Código Acesso'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='CPF'),
        ),
    ]
