# Generated by Django 2.0.2 on 2018-05-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20180504_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cod_acesso',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Código Acesso(RFB)'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Usuário'),
        ),
    ]
