# Generated by Django 2.0.2 on 2018-05-04 13:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Código')),
                ('razao', models.CharField(max_length=200, verbose_name='Razão/Nome')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('bairro', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('num', models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Número')),
                ('cep', models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='CEP')),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ/CPF')),
                ('ie', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Inscrição Estadual')),
                ('im', models.CharField(blank=True, max_length=10, null=True, verbose_name='Inscrição Municipal')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_status', models.CharField(max_length=50, verbose_name='Situação')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Tipo_status'),
        ),
    ]
