# Generated by Django 2.0.2 on 2018-05-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Código'),
        ),
    ]
