# Generated by Django 2.0.2 on 2018-05-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20180507_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ie',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Inscrição Estadual'),
        ),
    ]
